import math
import tempfile
import unittest

from atomstack.geometry import (Document, Shape, outside_bed, path_points, shape_bounds,
                                shape_paths)


class GeometryTests(unittest.TestCase):
    def test_rectangle_export_is_bounded_and_explicitly_disarms(self):
        document = Document()
        document.add(Shape("rectangle", 10, 20, 40, 30, speed=1200, power=425, passes=2))
        code = document.gcode((-288, -301))
        self.assertTrue(code.startswith("; Atomstack personal controller - machine-coordinate export\n; Confirmed machine origin: X-288.000 Y-301.000\nG21\nG90\nM5\nS0\n"))
        self.assertEqual(code.count("M4 S425"), 2)
        self.assertEqual(code.count("G53 G1 X-238.000 Y-281.000 F1200"), 2)
        self.assertTrue(code.endswith("M5\nS0\n; End - generated by Atomstack personal controller\n"))

    def test_geometry_may_sit_off_the_bed_but_cannot_be_sent(self):
        """An oversized import has to exist before it can be scaled to fit."""
        for shape in (Shape("rectangle", -1, 0, 1, 1), Shape("circle", 350, 0, 20, 10),
                      Shape("line", 0, 300, 5, 10)):
            with self.subTest(shape=shape):
                self.assertTrue(outside_bed(shape.validated()))
                document = Document()
                document.add(shape)
                self.assertEqual(len(document.offbed()), 1)
                for action, call in (("sending", lambda: document.gcode((0, 0))),
                                     ("framing", document.frame_points)):
                    with self.assertRaises(ValueError) as caught:
                        call()
                    self.assertIn("outside the", str(caught.exception))
                    self.assertIn(action, str(caught.exception))
        # Geometry with no extent is still refused outright: it is not geometry.
        with self.assertRaises(ValueError):
            Shape("rectangle", 0, 0, 0, 1).validated()

    def test_moving_an_oversized_object_back_on_the_bed_makes_it_sendable(self):
        document = Document()
        document.add(Shape("rectangle", 350, 0, 20, 10))
        with self.assertRaises(ValueError):
            document.gcode((0, 0))
        document.update(0, x=300)
        self.assertEqual(document.offbed(), ())
        self.assertIn("G53 G1", document.gcode((0, 0)))

    def test_the_refusal_names_the_objects_that_are_off_the_bed(self):
        document = Document()
        document.add(Shape("rectangle", 10, 10, 10, 10))
        document.add(Shape("rectangle", 350, 10, 20, 10))
        with self.assertRaises(ValueError) as caught:
            document.gcode((0, 0))
        self.assertIn("Object 2", str(caught.exception))

    def test_process_limits(self):
        for changes in ({"speed": 59}, {"speed": 20001}, {"power": -1}, {"power": 1001},
                        {"passes": 0}, {"passes": 21}):
            values = dict(kind="rectangle", x=0, y=0, width=1, height=1)
            values.update(changes)
            with self.subTest(changes=changes), self.assertRaises(ValueError):
                Shape(**values).validated()

    def test_circle_is_closed_and_stays_inside_ellipse(self):
        shape = Shape("circle", 10, 20, 40, 10)
        points = path_points(shape)
        self.assertEqual(len(points), 73)
        self.assertAlmostEqual(points[0][0], points[-1][0])
        self.assertAlmostEqual(points[0][1], points[-1][1])
        self.assertTrue(all(10 <= x <= 50 and 20 <= y <= 30 for x, y in points))

    def test_document_update_and_delete(self):
        document = Document()
        index = document.add(Shape("rectangle", 1, 2, 3, 4))
        document.update(index, x=5, power=0)
        self.assertEqual(document.shapes[0].x, 5)
        self.assertEqual(document.shapes[0].power, 0)
        document.delete(index)
        with self.assertRaises(ValueError):
            document.gcode()

    def test_export_requires_confirmed_origin(self):
        document = Document()
        document.add(Shape("line", 0, 0, 1, 1))
        with self.assertRaises(ValueError):
            document.gcode()

    def test_export_offsets_app_geometry_into_machine_coordinates(self):
        document = Document()
        document.add(Shape("line", 1, 2, 3, 4, speed=300, power=0))
        code = document.gcode((-288, -301))
        self.assertIn("G53 G0 X-287.000 Y-299.000", code)
        self.assertIn("G53 G1 X-284.000 Y-295.000 F300", code)

    def test_horizontal_and_vertical_lines_are_valid(self):
        horizontal = Shape("line", 10, 20, 40, 0).validated()
        vertical = Shape("line", 10, 20, 0, 40).validated()
        self.assertEqual(shape_paths(horizontal), [[(10, 20), (50, 20)]])
        self.assertEqual(shape_paths(vertical), [[(10, 20), (10, 60)]])
        with self.assertRaises(ValueError):
            Shape("line", 10, 20, 0, 0).validated()

    def test_rotation_and_mirroring_transform_exact_output_paths(self):
        rotated = Shape("rectangle", 10, 20, 40, 10, rotation=90).validated()
        self.assertEqual(tuple(round(value, 6) for value in shape_bounds(rotated)), (25.0, 5.0, 35.0, 45.0))
        mirrored = Shape("line", 10, 20, 20, 0, mirror_x=True).validated()
        self.assertEqual(shape_paths(mirrored), [[(30.0, 20.0), (10.0, 20.0)]])
        document = Document()
        document.add(rotated)
        code = document.gcode((0, 0))
        self.assertIn("G53 G0 X35.000 Y5.000", code)
        self.assertIn("G53 G1 X35.000 Y45.000", code)
        first = shape_paths(rotated)
        first[0][0] = (999, 999)
        self.assertNotEqual(shape_paths(rotated)[0][0], (999, 999))

    def test_transformed_bounds_are_enforced_and_used_for_frame(self):
        # Rotation can take a shape off the bed; that is judged when sending.
        self.assertTrue(outside_bed(Shape("rectangle", 0, 0, 40, 10, rotation=90).validated()))
        document = Document()
        document.add(Shape("rectangle", 10, 20, 40, 10, rotation=90))
        self.assertEqual(document.frame_points(0), ((25.0, 5.0), (35.0, 5.0), (35.0, 45.0), (25.0, 45.0), (25.0, 5.0)))
        with self.assertRaises(ValueError):
            Shape("rectangle", 10, 20, 40, 10, mirror_x="false").validated()

    def test_nonfinite_values_rejected(self):
        for value in (math.nan, math.inf, -math.inf):
            with self.assertRaises(ValueError):
                Shape("rectangle", value, 0, 1, 1).validated()

    def test_frame_outline_wraps_all_geometry_with_clamped_margin(self):
        document = Document()
        document.add(Shape("rectangle", 1, 2, 10, 20))
        document.add(Shape("line", 350, 290, 15, 15))
        self.assertEqual(document.frame_points(2),
                         ((0.0, 0.0), (365.0, 0.0), (365.0, 305.0), (0.0, 305.0), (0.0, 0.0)))

    def test_frame_outline_requires_geometry_and_valid_margin(self):
        document = Document()
        with self.assertRaises(ValueError):
            document.frame_points()
        document.add(Shape("rectangle", 10, 10, 10, 10))
        for margin in (-1, 21, math.nan):
            with self.subTest(margin=margin), self.assertRaises(ValueError):
                document.frame_points(margin)

    def test_text_is_vector_geometry_with_separate_closed_contours(self):
        shape = Shape("text", 10, 20, 60, 15, speed=900, power=250,
                      text="ATOM 10", font_family="Arial").validated()
        paths = shape_paths(shape)
        self.assertGreater(len(paths), 3)
        self.assertTrue(all(path for path in paths))
        self.assertTrue(all(10 <= x <= 70 and 20 <= y <= 35 for path in paths for x, y in path))
        document = Document()
        document.add(shape)
        code = document.gcode((-288, -301))
        self.assertIn("text 'ATOM 10'", code)
        self.assertEqual(code.count("M4 S250"), len(paths))

    def test_multi_line_text_cannot_escape_the_gcode_comment(self):
        """Text spans lines now, and the job writes it into a ';' comment."""
        document = Document()
        document.add(Shape("text", 10, 10, 40, 20, text="M3 S1000" + chr(10) + "G0 X999"))
        for line in document.gcode((0, 0)).splitlines():
            self.assertFalse(line.startswith(("M3", "G0 X999")), line)
        comments = [l for l in document.gcode((0, 0)).splitlines() if "M3 S1000" in l]
        self.assertTrue(comments)
        for comment in comments:
            self.assertTrue(comment.startswith(";"))
            self.assertIn("G0 X999", comment)   # kept, on the same comment line

    def test_text_validation_rejects_empty_or_unknown_font(self):
        for shape in (Shape("text", 0, 0, 10, 5, text=""),
                      Shape("text", 0, 0, 10, 5, text="Hello", font_family="Unknown"),
                      Shape("text", 0, 0, 10, 5, text="Hi", text_align="middle"),
                      Shape("text", 0, 0, 10, 5, text="Hi", line_spacing=9.0),
                      Shape("text", 0, 0, 10, 5, text="Hi", letter_spacing=-5.0)):
            with self.assertRaises(ValueError):
                shape.validated()

    def test_burn_test_grid_assigns_speed_by_column_and_power_by_row(self):
        document = Document()
        indices = document.add_burn_test(10, 15, 20, 12, [300, 600, 900], [100, 300])
        self.assertEqual(len(indices), 6)
        self.assertEqual([(s.speed, s.power) for s in document.shapes],
                         [(300, 100), (600, 100), (900, 100),
                          (300, 300), (600, 300), (900, 300)])
        self.assertEqual(document.shapes[-1].note, "F900 · S300")
        self.assertLessEqual(document.shapes[-1].x + document.shapes[-1].width, 365)

    def test_burn_test_grid_rejects_overflow_and_invalid_values(self):
        document = Document()
        # A grid that runs off the bed is built, then refused at the machine.
        document.add_burn_test(350, 300, 20, 12, [300, 600], [100, 300])
        self.assertTrue(document.offbed())
        with self.assertRaises(ValueError):
            document.gcode((0, 0))
        document.shapes.clear()
        with self.assertRaises(ValueError):
            document.add_burn_test(0, 0, 20, 12, [30], [100])

    def test_preview_segments_match_job_order_and_metrics(self):
        document = Document()
        document.add(Shape("line", 10, 0, 20, 0, speed=600, power=250, passes=2))
        segments = document.preview_segments()
        self.assertEqual([segment[0] for segment in segments], ["rapid", "burn", "rapid", "burn"])
        self.assertEqual(segments[0][1:3], ((0.0, 0.0), (10, 0)))
        self.assertEqual(segments[-1][1:3], ((10, 0), (30, 0)))
        metrics = document.job_metrics()
        self.assertEqual(metrics["rapid_distance"], 30)
        self.assertEqual(metrics["burn_distance"], 40)
        self.assertAlmostEqual(metrics["estimated_seconds"], 4.3)
        # A machine that rapids at 20,000 mm/min spends a tenth of that on travel.
        live = document.job_metrics(rapid_feed=20000)
        self.assertAlmostEqual(live["estimated_seconds"], 4.09)
        self.assertEqual(live["rapid_distance"], metrics["rapid_distance"])
        self.assertEqual(metrics["max_power"], 250)

    def test_preview_requires_geometry_and_finite_start(self):
        document = Document()
        with self.assertRaises(ValueError):
            document.preview_segments()
        document.add(Shape("rectangle", 0, 0, 10, 10))
        with self.assertRaises(ValueError):
            document.preview_segments((math.nan, 0))


if __name__ == "__main__":
    unittest.main()
